### ISSUE TITLE
Restore scroll position for  'unsuspended' tabs.

### ISSUE THREAD

**Issue by wehuty** [rNeomy/tab-suspender#21]
IMHO it'ld be useful for those who read pages that are more then screen height.

**Comment by szbnwer** [comment]
hi!

so i wanted to open a new issue, but what i would like to ask will resolve this as well, so after a few times of attempt to finish a long read, or just opening from pinned tabs links in new tabs and closing them can set you on a continuously suspended and unsuspended window just because other activities... the resoult is that you can't navigate back, to the origin like a search or a page where you cane from, because of the history will be erased... so my idea is to use navigate back for unsuspending, that would solve the issue with scroll, because the browser keeps that with the history, and the history also wont get lost this way - if its possible, as im not a browser haxxor, but i know javascript, but your codes were strange in some points for me, so ill let this idea here for you, and thcx very much!

anyway i just started to use your stuff and i like it so much! :)

**Comment by rNeomy** [comment]
This is implemented on 0.1.8. Thanks for the suggestion. To unsuspend, `history.back()` is used when possible which restores the old window and does not mess up history by duplicating an old url.
