### ISSUE TITLE
Tab Suspender theme uniformity/compatibility with Firefox container functionality

### ISSUE THREAD

**Issue by ivanruvalcaba** [rNeomy/tab-suspender#54]
Nice day!

I am currently using the extension with the dark theme enabled, however, there is no uniformity if any tabs are opened in any container as shown below.

Opened tab without container functionality enabled:

![tabsuspender1](https://user-images.githubusercontent.com/31249195/31259846-a9a1351e-aa0f-11e7-8c9f-65dcad1aba5e.jpg)

Opened tab with container functionality enabled:

![tabsuspender2](https://user-images.githubusercontent.com/31249195/31259848-afe8c84c-aa0f-11e7-9145-fe948d2375ee.jpg)

Screenshots were taken in Firefox Nightly (58.0a1) 64bit.

Best regards.

**Comment by hyunh90** [comment]
The dark mode [currently relies on the `localStorage`](https://github.com/rNeomy/tab-suspender/blob/master/data/suspend/index.js#L5), which is [isolated by the Container](https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers#What_is_.28and_isn.27t.29_separated_between_Containers).

This is just my guess, but according to [the MDN reference](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage), using `chrome.storage.local` instead of `localStorage` might fix this issue.

**Comment by rNeomy** [comment]
I am using `localStroage` to have the preference synchronously, otherwise we will get white and then black themes.
